config/routes.rb
Stella::Application.routes.draw do
  resources :characters

  devise_for :users
  match '/about',       to: 'static_pages#about',   via: 'get'
  match '/home',        to: 'static_pages#home',    via: 'get'
  match '/help',        to: 'static_pages#help',    via: 'get'
  match '/contact',     to: 'static_pages#contact', via: 'get'

  devise_scope :user do
    get "sign_in",      to: 'devise/sessions#new'
    delete "sign_out",  to: 'devise/sessions#destroy'
    get "sign_up",      to: 'devise/registrations#new'
  end

  get "static_pages/home"
  get "static_pages/help"
  get "static_pages/about"
  get "static_pages/contact"

  
  root "static_pages#home"

end

app/models/character.rb
class Character < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :character
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :have_char
  private
  	def have_char
  		if user_signed_in?
  			if action_name!='destroy'
	  			if controller_name!= 'characters' && controller_name!='devise/sessions'
	  				if current_user.character.nil?
	  					redirect_to new_character_path
	  				end
	  			end
	  		end
  		end
  	end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :set_character, only: [:show, :edit, :update, :destroy]

  # GET /characters
  # GET /characters.json
  def index
    @characters = Character.all
  end

  # GET /characters/1
  # GET /characters/1.json
  def show
  end

  # GET /characters/new
  def new
    @character = Character.new
  end

  # GET /characters/1/edit
  def edit
  end

  # POST /characters
  # POST /characters.json
  def create
    @character = Character.new(character_params)

    respond_to do |format|
      if @character.save
        format.html { redirect_to @character, notice: 'Character was successfully created.' }
        format.json { render action: 'show', status: :created, location: @character }
      else
        format.html { render action: 'new' }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /characters/1
  # PATCH/PUT /characters/1.json
  def update
    respond_to do |format|
      if @character.update(character_params)
        format.html { redirect_to @character, notice: 'Character was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /characters/1
  # DELETE /characters/1.json
  def destroy
    @character.destroy
    respond_to do |format|
      format.html { redirect_to characters_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_character
      @character = Character.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def character_params
      params.require(:character).permit(:user_id, :name, :surname, :pion, :joined, :town, :about, :hobbies, :points_all, :points, :krzyz, :naramiennik, :stop_instr, :stop_harc)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	#before_action :authenticate_user!
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :surname, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def logon_text
		if current_user.character.nil?
			current_user.email
		else
			current_user.character.name + ' ' + current_user.character.surname
		end
	end
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/characters/_form.html.erb
<%= form_for(@character) do |f| %>
  <% if @character.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@character.errors.count, "error") %> prohibited this character from being saved:</h2>

      <ul>
      <% @character.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :surname %><br>
    <%= f.text_field :surname %>
  </div>
  <div class="field">
    <%= f.label :pion %><br>
    <%= f.number_field :pion %>
  </div>
  <div class="field">
    <%= f.label :joined %><br>
    <%= f.date_select :joined %>
  </div>
  <div class="field">
    <%= f.label :town %><br>
    <%= f.text_field :town %>
  </div>
  <div class="field">
    <%= f.label :about %><br>
    <%= f.text_field :about %>
  </div>
  <div class="field">
    <%= f.label :hobbies %><br>
    <%= f.text_field :hobbies %>
  </div>
  <div class="field">
    <%= f.label :points_all %><br>
    <%= f.number_field :points_all %>
  </div>
  <div class="field">
    <%= f.label :points %><br>
    <%= f.number_field :points %>
  </div>
  <div class="field">
    <%= f.label :krzyz %><br>
    <%= f.check_box :krzyz %>
  </div>
  <div class="field">
    <%= f.label :naramiennik %><br>
    <%= f.check_box :naramiennik %>
  </div>
  <div class="field">
    <%= f.label :stop_instr %><br>
    <%= f.number_field :stop_instr %>
  </div>
  <div class="field">
    <%= f.label :stop_harc %><br>
    <%= f.number_field :stop_harc %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/characters/edit.html.erb
<h1>Editing character</h1>

<%= render 'form' %>

<%= link_to 'Show', @character %> |
<%= link_to 'Back', characters_path %>

app/views/characters/index.html.erb
<h1>Listing characters</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Name</th>
      <th>Surname</th>
      <th>Pion</th>
      <th>Joined</th>
      <th>Town</th>
      <th>About</th>
      <th>Hobbies</th>
      <th>Points all</th>
      <th>Points</th>
      <th>Krzyz</th>
      <th>Naramiennik</th>
      <th>Stop instr</th>
      <th>Stop harc</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @characters.each do |character| %>
      <tr>
        <td><%= character.user_id %></td>
        <td><%= character.name %></td>
        <td><%= character.surname %></td>
        <td><%= character.pion %></td>
        <td><%= character.joined %></td>
        <td><%= character.town %></td>
        <td><%= character.about %></td>
        <td><%= character.hobbies %></td>
        <td><%= character.points_all %></td>
        <td><%= character.points %></td>
        <td><%= character.krzyz %></td>
        <td><%= character.naramiennik %></td>
        <td><%= character.stop_instr %></td>
        <td><%= character.stop_harc %></td>
        <td><%= link_to 'Show', character %></td>
        <td><%= link_to 'Edit', edit_character_path(character) %></td>
        <td><%= link_to 'Destroy', character, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Character', new_character_path %>

app/views/characters/new.html.erb
<h1>New character</h1>

<%= render 'form' %>

<%= link_to 'Back', characters_path %>

app/views/characters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @character.user_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @character.name %>
</p>

<p>
  <strong>Surname:</strong>
  <%= @character.surname %>
</p>

<p>
  <strong>Pion:</strong>
  <%= @character.pion %>
</p>

<p>
  <strong>Joined:</strong>
  <%= @character.joined %>
</p>

<p>
  <strong>Town:</strong>
  <%= @character.town %>
</p>

<p>
  <strong>About:</strong>
  <%= @character.about %>
</p>

<p>
  <strong>Hobbies:</strong>
  <%= @character.hobbies %>
</p>

<p>
  <strong>Points all:</strong>
  <%= @character.points_all %>
</p>

<p>
  <strong>Points:</strong>
  <%= @character.points %>
</p>

<p>
  <strong>Krzyz:</strong>
  <%= @character.krzyz %>
</p>

<p>
  <strong>Naramiennik:</strong>
  <%= @character.naramiennik %>
</p>

<p>
  <strong>Stop instr:</strong>
  <%= @character.stop_instr %>
</p>

<p>
  <strong>Stop harc:</strong>
  <%= @character.stop_harc %>
</p>

<%= link_to 'Edit', edit_character_path(@character) %> |
<%= link_to 'Back', characters_path %>

app/views/layouts/_footer.html.erb
<div id="footer">
	<div class="container">
		<div class="row">
			<div class="col-md-4">
				Kontakt
			</div>
			<div class="col-md-4">
				Wsparcie
			</div>
			<div class="col-md-4">
				Społeczności
			</div>
		</div>
	</div>
</div>

app/views/layouts/_header.html.erb
<div class="row">
	<div class="col-md-8">
		<p>Logo</p>
	</div>
	<div class="col-md-4">
		<p>Szukajka</p>
	</div>
</div>

app/views/layouts/_nav_bar.html.erb
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Stella", root_path, class: "navbar-brand" %>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Contact", contact_path %></li>
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Help", help_path %></li>
          </ul>
          <% if user_signed_in? %>
          <p class="navbar-text">
            Zalogowany jako 
            <%# current_user.email %>
            <%= logon_text %>
            <%# current_user.character.name %> <%# current_user.character.surname %> 
            <%= link_to "Wyloguj", sign_out_path, method: :delete %>
          </p>
          <% else %>
          <p class="navbar-text">
            <%= link_to "Zaloguj", sign_in_path %>
          </p>
          <% end %>
        </div><!--/.nav-collapse -->
      </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stella</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<%= render 'layouts/nav_bar' %>
    <div class="container">
    	<% #render 'layouts/header' %>
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
        <%= yield %>

    </div>
     <%= render 'layouts/footer' %>
</body>
</html>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<h1>Stella Home</h1>
<p>Stella home page.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Proin nibh augue, suscipit a, scelerisque sed, lacinia in, mi. Cras vel lorem. Etiam pellentesque aliquet tellus. Phasellus pharetra nulla ac diam. Quisque semper justo at risus. Donec venenatis, turpis vel hendrerit interdum, dui ligula ultricies purus, sed posuere libero dui id orci. Nam congue, pede vitae dapibus aliquet, elit magna vulputate arcu, vel tempus metus leo non est. Etiam sit amet lectus quis est congue mollis. Phasellus congue lacus eget neque. Phasellus ornare, ante vitae consectetuer consequat, purus sapien ultricies dolor, et mollis pede metus eget nisi. Praesent sodales velit quis augue. Cras suscipit, urna at aliquam rhoncus, urna quam viverra nisi, in interdum massa nibh nec erat.</p>